name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - run: flutter pub get
      
      - run: flutter doctor -v

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: ls -la
        working-directory: build/ios/iphoneos

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: 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
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: build-${{ github.run_number }}
          overwrite: true
          body: |
            🎉 iOS Release Build
            - Build Number: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
